services:
  imgproxy:
    image: darthsim/imgproxy:latest
    restart: always
    ports:
      - "8081:8080"
    environment:
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_ALLOW_INSECURE_URLS: "true"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /images
      IMGPROXY_USE_S3: "true"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - "/home/test_image-server/Photos:/images"
